### ISSUE TITLE
Tạo Schema và Type cho GraphQL

### ISSUE THREAD

**Issue by yunsi2606** [CoderSaiya/BE_XDPMHDT#10]
# Implement GraphQL for Freelance Marketplace Models

## Description
We need to implement GraphQL types, queries, and mutations for our Freelance Marketplace models in our .NET 6.0 project. This includes setting up the necessary configurations in the `Program.cs` file.

## Models to Implement
- Apply
- Category
- Contract
- Payment
- Project
- Review
- Notification
- Img
- User
- UserProfile

##Task Assignments

- Apply: @VOMINHTIEN11022004 
- Category & Project: @thienhuyz 
- Payment & Review: @ThaiBinh2004 
- UserProfile & Notification: @PhucHau0310 
- User & Contract & Img: @CoderSaiya

### 1. Create GraphQL Types

For each model, create a corresponding GraphQL type. Here's an example for the User model:

```csharp
public class UserType : ObjectGraphType<User>
{
    public UserType()
    {
        Field(u => u.Id);
        Field(u => u.Username);
        Field(u => u.Email);
        Field(u => u.Role);
        Field<ListGraphType<ProjectType>>("projects", resolve: context => context.Source.Projects);
    }
}
```

**TODO:** Create similar types for Apply, Category, Contract, Payment, Project, and Review.

### 2. Implement Queries

Create query classes for each model. Example for User:

```csharp
public class UserQueries : ObjectGraphType
{
    public UserQueries(IUserService userService)
    {
        Field<UserType>("user")
            .Arguments(new QueryArguments(new QueryArgument<NonNullGraphType<IdGraphType>> { Name = "id" }))
            .Resolve(context =>
            {
                var id = context.GetArgument<int>("id");
                return userService.GetUserById(id);
            });

        Field<ListGraphType<UserType>>("users")
            .Resolve(context => userService.GetAllUsers());
    }
}
```

**TODO:** Implement similar queries for other models.

### 3. Implement Mutations

Create mutation classes for each model. Example for User:

```csharp
public class UserMutations : ObjectGraphType
{
    public UserMutations(IUserService userService)
    {
        Field<UserType>("createUser")
            .Arguments(
                new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "username" },
                new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "email" },
                new QueryArgument<NonNullGraphType<StringGraphType>> { Name = "password" }
            )
            .Resolve(context =>
            {
                var username = context.GetArgument<string>("username");
                var email = context.GetArgument<string>("email");
                var password = context.GetArgument<string>("password");
                return userService.CreateUser(username, email, password);
            });

        // Add more mutations (updateUser, deleteUser, etc.)
    }
}
```

**TODO:** Implement similar mutations for other models.

### 4. Update Program.cs

Update the `Program.cs` file to include GraphQL configuration:

```csharp
// Register GraphQL types with scoped lifetime
builder.Services.AddScoped<UserQuery>();

builder.Services.AddScoped<UserMutation>();

builder.Services.AddScoped<UserType>();
```

### 5. Create Main Schema

Create a `MainSchema.cs` file to combine all queries and mutations:

```csharp
public class MainSchema : Schema
    {
        public MainSchema(IServiceProvider serviceProvider) : base(serviceProvider)
        {
            Query = serviceProvider.GetRequiredService<UserQuery>();
            Mutation = serviceProvider.GetRequiredService<UserMutation>();
        }
    }
```

## References
- GraphQL: [graphql-link](https://graphql-aspnet.github.io/)

## Acceptance Criteria
- [ ] GraphQL types are created for all models
- [ ] Queries are implemented for all models
- [ ] Mutations are implemented for all models
- [ ] `Program.cs` is updated with GraphQL configuration
- [ ] Root schema is created and combines all queries and mutations
- [ ] GraphQL endpoint is working and can be tested with GraphQL Playground

## Additional Notes
- Ensure proper error handling and validation in resolvers
- Consider implementing DataLoader for optimizing nested queries
- Add authentication and authorization checks where necessary
